# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.8.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.8.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/apple/Desktop/计算摄影学/PhotoMontage/PhotoMontage

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/apple/Desktop/计算摄影学/PhotoMontage/PhotoMontage

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.8.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.8.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/apple/Desktop/计算摄影学/PhotoMontage/PhotoMontage/CMakeFiles /Users/apple/Desktop/计算摄影学/PhotoMontage/PhotoMontage/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/apple/Desktop/计算摄影学/PhotoMontage/PhotoMontage/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named project

# Build rule for target.
project: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 project
.PHONY : project

# fast build rule for target.
project/fast:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/build
.PHONY : project/fast

# target to build an object file
ConjGrad.o:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/ConjGrad.o
.PHONY : ConjGrad.o

# target to preprocess a source file
ConjGrad.i:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/ConjGrad.i
.PHONY : ConjGrad.i

# target to generate assembly for a file
ConjGrad.s:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/ConjGrad.s
.PHONY : ConjGrad.s

# target to build an object file
GCoptimization.o:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/GCoptimization.o
.PHONY : GCoptimization.o

# target to preprocess a source file
GCoptimization.i:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/GCoptimization.i
.PHONY : GCoptimization.i

# target to generate assembly for a file
GCoptimization.s:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/GCoptimization.s
.PHONY : GCoptimization.s

# target to build an object file
LinkedBlockList.o:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/LinkedBlockList.o
.PHONY : LinkedBlockList.o

# target to preprocess a source file
LinkedBlockList.i:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/LinkedBlockList.i
.PHONY : LinkedBlockList.i

# target to generate assembly for a file
LinkedBlockList.s:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/LinkedBlockList.s
.PHONY : LinkedBlockList.s

# target to build an object file
LoadLib.o:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/LoadLib.o
.PHONY : LoadLib.o

# target to preprocess a source file
LoadLib.i:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/LoadLib.i
.PHONY : LoadLib.i

# target to generate assembly for a file
LoadLib.s:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/LoadLib.s
.PHONY : LoadLib.s

# target to build an object file
PhotoMontage.o:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/PhotoMontage.o
.PHONY : PhotoMontage.o

# target to preprocess a source file
PhotoMontage.i:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/PhotoMontage.i
.PHONY : PhotoMontage.i

# target to generate assembly for a file
PhotoMontage.s:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/PhotoMontage.s
.PHONY : PhotoMontage.s

# target to build an object file
graph.o:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/graph.o
.PHONY : graph.o

# target to preprocess a source file
graph.i:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/graph.i
.PHONY : graph.i

# target to generate assembly for a file
graph.s:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/graph.s
.PHONY : graph.s

# target to build an object file
main.o:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/main.o
.PHONY : main.o

# target to preprocess a source file
main.i:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/main.i
.PHONY : main.i

# target to generate assembly for a file
main.s:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/main.s
.PHONY : main.s

# target to build an object file
maxflow.o:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/maxflow.o
.PHONY : maxflow.o

# target to preprocess a source file
maxflow.i:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/maxflow.i
.PHONY : maxflow.i

# target to generate assembly for a file
maxflow.s:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/maxflow.s
.PHONY : maxflow.s

# target to build an object file
stdafx.o:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/stdafx.o
.PHONY : stdafx.o

# target to preprocess a source file
stdafx.i:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/stdafx.i
.PHONY : stdafx.i

# target to generate assembly for a file
stdafx.s:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/stdafx.s
.PHONY : stdafx.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... project"
	@echo "... ConjGrad.o"
	@echo "... ConjGrad.i"
	@echo "... ConjGrad.s"
	@echo "... GCoptimization.o"
	@echo "... GCoptimization.i"
	@echo "... GCoptimization.s"
	@echo "... LinkedBlockList.o"
	@echo "... LinkedBlockList.i"
	@echo "... LinkedBlockList.s"
	@echo "... LoadLib.o"
	@echo "... LoadLib.i"
	@echo "... LoadLib.s"
	@echo "... PhotoMontage.o"
	@echo "... PhotoMontage.i"
	@echo "... PhotoMontage.s"
	@echo "... graph.o"
	@echo "... graph.i"
	@echo "... graph.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... maxflow.o"
	@echo "... maxflow.i"
	@echo "... maxflow.s"
	@echo "... stdafx.o"
	@echo "... stdafx.i"
	@echo "... stdafx.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

